### ISSUE TITLE
Some samples aren't processed

### ISSUE THREAD

**Issue by chbk** [nf-core/atacseq#142]
In the MultiQC report, only one of the samples appears in the following sections:
- MERGED LIB: PICARD
- MERGED LIB: deepTools: Read Distribution Profile after Annotation
- MERGED LIB: HOMER peak annotation
- MERGED REP: HOMER peak annotation

Compare:

![a](https://user-images.githubusercontent.com/7478535/107260905-ef493100-6a3e-11eb-9be2-6f48e87e4d7b.png)
![b](https://user-images.githubusercontent.com/7478535/107260910-f112f480-6a3e-11eb-9e85-2d0519a4de95.png)
![c](https://user-images.githubusercontent.com/7478535/107260913-f1ab8b00-6a3e-11eb-9088-934ef26a4169.png)

With:

![d](https://user-images.githubusercontent.com/7478535/107260914-f2442180-6a3e-11eb-9ca9-9e39302a4b82.png)

**Comment by chbk** [comment]
Upon further investigation, it appears only one of the files in the channels is processed.
This is because the input channels do not have the same lengths: https://github.com/nf-core/atacseq/blob/1b3a832db5a53c92c2c89a4d6d79455e860461ad/main.nf#L958 https://github.com/nf-core/atacseq/blob/1b3a832db5a53c92c2c89a4d6d79455e860461ad/main.nf#L959

A workaround would be:

```groovy
tuple val(name), path(bam), path(fasta) from ch_mlib_rm_orphan_bam_metrics.combine(ch_fasta)
```

**Comment by drpatelh** [comment]
Hi @chbk ! Thank you for creating this issue. This is quite odd because the the full-tests we run on pipeline release have the correct sections in the [MultiQC report](https://nf-core-awsmegatests.s3-eu-west-1.amazonaws.com/atacseq/results-1b3a832db5a53c92c2c89a4d6d79455e860461ad/multiqc/broadPeak/multiqc_report.html#picard). But I agree that something isn't clearly right. I think it may be better to troubleshoot on Slack in real-time. If you aren't a member you can join [here](https://nf-co.re/join) and post on the #atacseq channel.

**Comment by drpatelh** [comment]
Hi @chbk ! We are about to release a much updated version of the pipeline that has been completely refactored to be written in Nextflow DSL2. When this is released, it would be great if you can let us know if the problem still persists. I will close this issue for now.
