### ISSUE TITLE
Signal always higher in one condition

### ISSUE THREAD

**Issue by Cristinex** [nf-core/atacseq#160]
Hi, All,

I have been trapped by a problem which I found that one condition of my data has signals always higher than the other. I discovered this phenomenon by browsing at UCSC genome browser. I get some information from the internet, telling that it could be the result of no normalization. However, to my understanding, the bigwig file outputs by nf-core/atac-seq are all normalized. Do you have any idea about what was wrong?

Appreciated.

**Comment by drpatelh** [comment]
Hi @Cristinex ! Thanks for reporting and apologies for the delay in responding! Yes, the bigWig files are normalised by read depth as outlined in the docs:
https://nf-co.re/atacseq/1.2.2/output#normalised-bigwig-files

Did you get to the bottom of the issue? It looks like it is sample rather than pipeline related so will close this issue. We are about to release a much updated version of the pipeline that has been completely refactored to be written in Nextflow DSL2. 

For faster, real-time help for these sorts of things please join the #atacseq channel on the nf-core Slack workspace. You can join via the link below:
https://nf-co.re/join
