### ISSUE TITLE
TSS heatmap inconsistency between ChIPseeker and nf-core ATAC-seq pipeline

### ISSUE THREAD

**Issue by hyjforesight** [nf-core/atacseq#193]
Hello ATAC-seq pipeline,
Previously, we did the ATAC-seq analysis manually by trimming adapters (Adapterremoval), alignment (Bowtie2), QC (remove blacklist, duplicates, unmapped reads, mito genes…), peak calling (MACS2), and peak annotation (ChIPseeker).

Luckily, we found this amazing and easy-to-use ATAC-seq pipeline on nf-core. We tried this pipeline and it works super great.

However, we are confused with 2 issues:
1.	The TSS heatmaps are inconsistent between our ChIPseeker results and nf-core ATAC-seq pipeline. In our hands, we can see heatmaps with signals, but the pipeline shows no signal at all. Which heatmap is right?
![Heatmap](https://user-images.githubusercontent.com/75048821/189773680-58eabcdc-b29c-4cf0-883a-a230c229b128.jpg)

2.	We found that the pipeline only calls broad peak, but ENCODE ATAC-seq pipeline calls narrow peak. Why does nf-core pipeline only call broad peak?
![broadpeak](https://user-images.githubusercontent.com/75048821/189773733-87c4b815-36d3-433b-b029-26da86cb9996.PNG)

Thank you!
Best,
Yuanjian Huang

**Comment by bjlang** [comment]
With respect to your 2nd issue:
The pipeline defaults to calling broad peaks. To activate narrowPeak mode, use `--narrow_peak` (see https://nf-co.re/atacseq/1.2.2/parameters#peak-calling-options)

**Comment by lnblum** [comment]
I've experienced the same issue. I think it has to do with the genes.tss.bed file. I swapped it out for refTSS (attached below - refTSS_v3.1_human_coordinate.hg38.bed) and got a result that makes sense.  I have not been able to diagnose the problem with genes.tss.bed but maybe deeptools is looking at the wrong columns in the bed file?
[50K-15-S-40-CEB_R1.plotHeatmap.pdf](https://github.com/nf-core/atacseq/files/10003916/50K-15-S-40-CEB_R1.plotHeatmap.pdf)
[50K-15-S-40-CEB_R1.mLb.clN.plotHeatmap.pdf](https://github.com/nf-core/atacseq/files/10003920/50K-15-S-40-CEB_R1.mLb.clN.plotHeatmap.pdf)
[refTSS_v3.1_human_coordinate.hg38.bed.txt](https://github.com/nf-core/atacseq/files/10003957/refTSS_v3.1_human_coordinate.hg38.bed.txt)

**Comment by robsyme** [comment]
There are three issues, I think:

1) We are supplying the gene bed rather than a TSS bed, which is the primary cause of the poor results.
2) We are not using the `--missingDataAsZero` parameter to `computeMatrix scale-regions`
3) Even if we switched the bed file to the TSS bed emitted in `PREPARE_GENOME.out.tss_bed`, that would not work as the bin width in `computeMatrix scale-regions` is 10bp and so the 1bp wide regions in `PREPARE_GENOME.out.tss_bed` would all be filtered out.

I'd suggest that we use the `PREPARE_GENOME.out.tss_bed` file, but expand all regions to at least 10 bp. This would involve either some awk magic in the `DEEPTOOLS_COMPUTEMATRIX` process, or an upstream `bedtools` process that then feeds into `DEEPTOOLS_COMPUTEMATRIX`.

If we expand the `PREPARE_GENOME.out.tss_bed` so that it meets the computeMatrix bin width minimum, we get sensible results that look like the heatmap attached.

![expanded GM12878_FAST_1 mLb clN](https://user-images.githubusercontent.com/31576/202964534-6ee7db14-3945-4446-b90b-9e2ecd02fd41.png)

**Comment by drpatelh** [comment]
Fixed in https://github.com/nf-core/atacseq/pull/228

Be great if you can confirm by trying out the code on the  `dev` branch. We are still fixing some stuff there but the plots should be generated as expected.

```
nextflow pull nf-core/atacseq -r dev
nextflow run nf-core/atacseq <YOUR_OPTIONS> -r dev
```

**Comment by lnblum** [comment]
Can confirm.  I ran the dev version on some data last week and the heatmaps were generated as expected.

**Comment by hyjforesight** [comment]
Hello @drpatelh 
Thank you for fixing the issue!

Could you please let me know how to adjust the scale bars to the same scale between different samples? Now they're 1.6, 1.72, 1.2 and 1.2.

<img width="451" alt="image" src="https://github.com/nf-core/atacseq/assets/75048821/8dba9830-7311-456e-9977-a079ca624677">

Thank you in advance!
