### ISSUE TITLE
Error executing process > 'output_documentation'

### ISSUE THREAD

**Issue by Will19902225** [nf-core/atacseq#208]
(base) huanglabdell@huanglabdell-Precision-7820-Tower:~$ nextflow run nf-core/atacseq -r 1.2.2 -profile test --outdir /media/huanglabdell/NGS_data_d3/NGS_data_drive_3_2022/NF_core_test/

WARN: Got an interrupted exception while taking agent result | java.lang.InterruptedException
Error executing process > 'output_documentation'

Caused by:
  Process `output_documentation` terminated with an error exit status (1)

Command executed:

  markdown_to_html.py output.md -o results_description.html

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/home/huanglabdell/.nextflow/assets/nf-core/atacseq/bin/markdown_to_html.py", line 4, in <module>
      import markdown
  ModuleNotFoundError: No module named 'markdown'

Work dir:
  /home/huanglabdell/work/e2/fa941a2af7a237d0c8614cefb38e1d

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

java.nio.channels.ClosedByInterruptException

**Comment by JoseEspinosa** [comment]
You missed in your command the profile that will tell the pipeline to use a container technology to run the pipeline (eg: `-profile test,singularity`). That is why the process complains of markdown not being installed in your system since it will be available in the container instead. I close the issue since I think this will solve your problem but if you find any other issue feel free to reopen it or create a new one.
