### ISSUE TITLE
nf-core atacseq version 2.0 doesn't perform deseq2 pairwise comparison

### ISSUE THREAD

**Issue by SereFe** [nf-core/atacseq#299]
### Description of the bug

Hi all,
I performed ATACeq analyses on two differen datasets, both of them have 2 groups of samples and 6 replicates/group. I launched the pipeline version 2.0, the pipeline completed successfully (both broad and narrow-peak) for both dataset but NO pairwise comparisons between the groups were performed. The deseq2 folder doesn't contained any pairwise comparison result. 
Several months ago I analyzed the same datasets with version 1.2.1 and I got pairwise comparisons.  I cannot understand why the new pipeline doesn't provide them even if they should be performed by default.

I attach below the command I used:
nextflow run nf-core/atacseq -r 2.0 --input /mnt/nfs/home/elab/ATAC_Vivo/Vivo_NoVibrio_SampleSheet2.csv --fasta /mnt/nfs/
home/elab/NCBI/Dlab_ncbi.fa --gtf /mnt/nfs/home/elab/NCBI/genomic_edited.gtf --macs_gsize 900000000 --save_
reference --save_trimmed --outdir /mnt/nfs/home/elab/ATAC_Vivo/Results/ -profile docker --max_cpus 24 --max_memory 100GB

Thank you
Serena

### System information

nextflow version 23.04.1.5866
Container engine Docker
OS Ubuntu 
nf-core/atacseq v 2.0

**Comment by JoseEspinosa** [comment]
I am afraid this pipeline no longer performs differential analysis since v2.0 as described [here](https://github.com/nf-core/atacseq/blob/master/CHANGELOG.md#warning-major-enhancements). The reason is that there are other pipelines such as [differentialabundance](https://nf-co.re/differentialabundance) that are being developed specifically to cover this kind of analysis so that the experimental design and statistical tests are taken into account in an appropriate manner. It is true that this has not been weel described in the docs :cry:  but this is now fixed on the `dev` version.

**Comment by JoseEspinosa** [comment]
You can actually find the [consensus peak read counts matrix](https://nf-co.re/atacseq/2.0/docs/output#create-and-quantify-consensus-set-of-peaks) from this pipeline and feed this as input to nf-core/differentialabundance let us know if you have any further question. Will close this issue now.
