### ISSUE TITLE
HOMER number of peaks does not correspond to found MACS2 peaks

### ISSUE THREAD

**Issue by ktrns** [nf-core/atacseq#50]
Hi again, 

We found that the cumulative number of peaks in the HOMER plot in the MultiQC report does not correspond to the found number of peaks by MACS2. Is this expected, and if so why?

Many thanks in advance!
Katrin

**Comment by drpatelh** [comment]
Hi @ktrns . How much is it off by?

Can you navigate to the peak folder for that sample:
`cd results/bwa/mergedLibrary/macs/`

and run the command below?
`cut -f 8 <SAMPLE_ID>.mLb.clN_peaks.annotatePeaks.txt | cut -d ' ' -f 1 | sort | uniq -c`

That should give you a breakdown of how many peaks per feature from the output file itself. Are you able to spot any discrepancies?

It may be because HOMER uses NA values for some peaks its unable to annotate...

**Comment by ktrns** [comment]
The HOMER figure sums up to more peaks than were found by MACS. I will check what you suggested and let you know. Thanks!

**Comment by ktrns** [comment]
Hi again. Macs called 245 peaks. Running the command above and counting the numbers together, I get 245! The MultiQC HOMER figure though, sums up to much more. 

BUT I just found the numbers I am expecting based on your command, in the HOMER figure for another sample. So it looks as if the sample labels are swapped in the figure.

**Comment by drpatelh** [comment]
Hi @ktrns ! This is indeed a bug. Ill get to the bottom of it and it will be fixed in the next release (hopefully soon!). Thanks for reporting.

245 is an awfully low number of peaks? Did something go wrong with the sample/library prep?

**Comment by drpatelh** [comment]
Fixed in https://github.com/nf-core/atacseq/pull/52
