### ISSUE TITLE
MakeGenomeFilter (genome.fa) terminated with an error status

### ISSUE THREAD

**Issue by dshechter** [nf-core/atacseq#98]
I'm running this pipeline on some fresh data. i ran the command with -profile test,docker first and it ran fine. When using my own data, and calling the GRCh37 genome, I got the error below:

> Error executing process > 'MakeGenomeFilter (genome.fa)'
> Caused by:
> Process `MakeGenomeFilter (genome.fa)` terminated with an error exit status (1)
> Command executed:    samtools faidx genome.fa
> 	get_autosomes.py genome.fa.fai genome.fa.autosomes.txt
> cut -f 1,2 genome.fa.fai > genome.fa.sizes                                     
> sortBed -i GRCh37-blacklist.bed -g genome.fa.sizes | complementBed -i stdin -g genome.fa.sizes | awk '$1 !~ /MT/ {print $0}' > genome.fa.include_regions.bed
> Command exit status: 1
> 
> Command output:
>   (empty)
> 
> Command error:
>   Chromosome "10" undefined in genome.fa.sizes
> 
> Work dir:
>   /mnt/raid/NGS/NGS_Data/atac-seq/202003/work/4b/01edf45b37d8895f82a7aa06192525
> 
> Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

everything else seems to be running fine (in fact trimgalore is still going):

> [52/d04e45] process > MakeTSSBED                        [100%] 1 of 1 ✔
> executor >  local (20)
> [e2/07c3c6] process > CheckDesign                       [100%] 1 of 1, cached: 1 ✔
> [52/d04e45] process > MakeTSSBED                        [100%] 1 of 1 ✔
> [4b/01edf4] process > MakeGenomeFilter                  [100%] 1 of 1, failed: 1 ✘
> [63/d0471e] process > FastQC                            [100%] 8 of 8 ✔
> [6a/2b8d20] process > TrimGalore                        [ 63%] 5 of 8
> [-        ] process > BWAMem                            [  0%] 0 of 1

Any ideas? I'm running under a local user, permissions are all fine.

**Comment by drpatelh** [comment]
Hi @dshechter! This is most likely because there was an issue with the download of the reference genome whilst the pipeline was running. If possible I would suggest that you download the genome bundle for GRCh37 from AWS iGenomes beforehand and then change the `--igenomes_base` parameter to point the pipeline to your local copy:
https://ewels.github.io/AWS-iGenomes/

This is how that parameter will be used to obtain the reference file paths:
https://github.com/nf-core/atacseq/blob/master/conf/igenomes.config

This way you are only downloading the reference which is much more storage friendly, and can then use a similar approach for any nf-core pipeline that uses AWS iGenomes.

Ill close this for now but please feel free to re-open if the issue persists 👍
